// Command genpins writes pins_gen.go: the strict tier of the build check.
//
// The strict tier is celestia-app plus the modules that provide packages in
// the import graph of the Fibre encoding path, limited to modules linked on
// every platform of the matrix below. It resolves from the module cache only.
//
// Regenerate with
//
//	go -C fibre generate ./fibrecommit
//
// Bumping a strict module changes what the commitment vectors were produced
// with: re-run the vector generator and get human sign-off before committing
// the new pins.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"sort"
)

const appModule = "github.com/celestiaorg/celestia-app/v10"

// roots are the packages of the encoding path: the row layout, the
// erasure-code and Merkle commitment, and the protocol parameter math.
var roots = []string{
	appModule + "/pkg/rsema1d",
	appModule + "/fibre/internal/row",
	"github.com/cometbft/cometbft/libs/math",
}

// excluded modules are linked by the encoding path but only detect CPU
// features; they follow the consumer's own dependency graph and must not
// pin it. The self-test guards the encoder behaviour.
var excluded = map[string]bool{
	"github.com/klauspost/cpuid/v2": true,
	"golang.org/x/sys":              true,
}

type platform struct{ goos, goarch, cgo string }

var matrix = func() []platform {
	var m []platform
	for _, os := range []string{"darwin", "linux"} {
		for _, arch := range []string{"amd64", "arm64"} {
			for _, cgo := range []string{"0", "1"} {
				m = append(m, platform{os, arch, cgo})
			}
		}
	}
	return m
}()

type module struct {
	Path    string
	Version string
	Sum     string
	Replace *module
}

type pkg struct {
	Module *module
}

type pin struct {
	version, sum, replacePath string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genpins:", err)
		os.Exit(1)
	}
}

func run() error {
	var strict map[string]pin
	for _, pl := range matrix {
		mods, err := list(pl)
		if err != nil {
			return fmt.Errorf("%s/%s cgo=%s: %w", pl.goos, pl.goarch, pl.cgo, err)
		}
		if strict == nil {
			strict = mods
			continue
		}
		for p, m := range strict {
			o, ok := mods[p]
			switch {
			case !ok:
				delete(strict, p)
			case o != m:
				return fmt.Errorf("%s differs between platforms", p)
			}
		}
	}
	if _, ok := strict[appModule]; !ok {
		return fmt.Errorf("%s is not linked on every platform", appModule)
	}
	paths := make([]string, 0, len(strict))
	for p := range strict {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/genpins; DO NOT EDIT.\n\npackage fibrecommit\n\n")
	b.WriteString("var pinnedModules = []pinnedModule{\n")
	for _, p := range paths {
		m := strict[p]
		fmt.Fprintf(&b, "\t{path: %q, version: %q, sum: %q, replacePath: %q},\n", p, m.version, m.sum, m.replacePath)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile("pins_gen.go", src, 0o644)
}

func list(pl platform) (map[string]pin, error) {
	args := append([]string{"list", "-mod=readonly", "-deps", "-json"}, roots...)
	cmd := exec.Command("go", args...)
	cmd.Env = append(os.Environ(),
		"GOPROXY=off", "GOFLAGS=", "GOWORK=off",
		"GOOS="+pl.goos, "GOARCH="+pl.goarch, "CGO_ENABLED="+pl.cgo)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list: %w", err)
	}
	mods := map[string]pin{}
	dec := json.NewDecoder(bytes.NewReader(out))
	for dec.More() {
		var p pkg
		if err := dec.Decode(&p); err != nil {
			return nil, fmt.Errorf("decode: %w", err)
		}
		if p.Module == nil || excluded[p.Module.Path] {
			continue
		}
		m := *p.Module
		eff := m
		repl := ""
		if m.Replace != nil {
			eff = *m.Replace
			repl = m.Replace.Path
		}
		if eff.Version == "" || eff.Sum == "" {
			return nil, fmt.Errorf("%s: no version or sum in the module cache", m.Path)
		}
		mods[m.Path] = pin{version: eff.Version, sum: eff.Sum, replacePath: repl}
	}
	return mods, nil
}
