// Command genpins writes pins_gen.go: version and h1 sum of celestia-app and
// of every module the upstream fibre package links, as resolved from the
// module cache (no network). Run it through go generate after bumping the
// celestia-app pin or its replace set.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"sort"
)

const appModule = "github.com/celestiaorg/celestia-app/v10"

type module struct {
	Path    string
	Version string
	Sum     string
	Replace *module
}

type pkg struct {
	Module *module
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "genpins:", err)
		os.Exit(1)
	}
}

func run() error {
	cmd := exec.Command("go", "list", "-deps", "-json", appModule+"/fibre")
	cmd.Env = append(os.Environ(), "GOPROXY=off", "GOFLAGS=-mod=mod")
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("go list: %w", err)
	}
	mods := map[string]module{}
	dec := json.NewDecoder(bytes.NewReader(out))
	for dec.More() {
		var p pkg
		if err := dec.Decode(&p); err != nil {
			return fmt.Errorf("decode: %w", err)
		}
		if p.Module == nil {
			continue
		}
		m := *p.Module
		eff := m
		repl := ""
		if m.Replace != nil {
			eff = *m.Replace
			repl = m.Replace.Path
		}
		if eff.Version == "" || eff.Sum == "" {
			return fmt.Errorf("%s: no version or sum in the module cache", m.Path)
		}
		mods[m.Path] = module{Path: m.Path, Version: eff.Version, Sum: eff.Sum, Replace: &module{Path: repl}}
	}
	if _, ok := mods[appModule]; !ok {
		return fmt.Errorf("%s is not a dependency of its fibre package", appModule)
	}
	paths := make([]string, 0, len(mods))
	for p := range mods {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/genpins; DO NOT EDIT.\n\npackage fibrecommit\n\n")
	b.WriteString("var pinnedModules = []pinnedModule{\n")
	for _, p := range paths {
		m := mods[p]
		fmt.Fprintf(&b, "\t{path: %q, version: %q, sum: %q, replacePath: %q},\n", m.Path, m.Version, m.Sum, m.Replace.Path)
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile("pins_gen.go", src, 0o644)
}
